import React from "react";
import Header6 from "@/components/headers/Header6";
import Footer2 from "@/components/footers/Footer2";
import { siteContent } from "@/data/siteContent";

export const metadata = {
  // Dynamically set title using siteContent
  title: `Terms of Service | ${siteContent.agent.name} - ${siteContent.agent.title}`,
  description: `Terms of Service for ${siteContent.agent.name}'s website.`,
};

export default function TermsOfServicePage() {
  // Dynamically replace placeholders in the title
  const pageTitle = metadata.title
    .replace('{Agent Name}', siteContent.agent.name)
    .replace('{Agent Title}', siteContent.agent.title);

  return (
    <>
      <div id="wrapper">
        <Header6 />
        <div className="main-content" style={{ paddingTop: '100px', paddingBottom: '100px' }}>
          <div className="tf-container">
            <div className="row">
              <div className="col-md-12">
                <h2 className="title-heading mb-10">Terms of Use</h2>
                <h3 className="mb-20">Terms Of Service Agreement</h3>
                <p className="mb-20">By using this web site, you are agreeing to comply and be bound by the following terms of service and use. Please review the following terms in their entirety and ensure their comprehension before using and viewing this web site.</p>

                <h4 className="mb-10">Spammers Not Welcome Here!</h4>
                <p className="mb-20"><strong>Spam Policy</strong> - This should go without saying, but we'll say it anyway: it's not OK to spam us, create fake accounts, scrap/copy our data and content. If you try, we will immediately close your {siteContent.agent.name}'s Website account.</p>

                <p className="mb-10">The terms “us”, “we”, “our”, or “owners” refers to “{siteContent.agent.name}'s Website” and the administrative operators of this web site, {siteContent.agent.name}. “You” refers to the user or viewer of this web site.</p>

                <p className="mb-10">That this “Terms of Use“ does not impose a financial obligation on you or create any representation agreement between you and {siteContent.agent.name}.</p>

                <p className="mb-20">{siteContent.agent.name}'s Website is an Affiliated VOW Partner on behalf of {siteContent.agent.name} {siteContent.agent.brokerageName} in Ontario. All MLS® Listing data is intended only for your personal, non-commercial use. Users must have a bona fide interest in the purchase, sale, or lease of real estate of the type being offered through this VOW. All registrants agree that you will not copy, redistribute, retransmit, or otherwise use any of the data or Listing Information provided, except in connection with your consideration of the purchase, sale, or lease of an individual property.</p>

                <h4 className="mb-10">Toronto Real Estate Board's Disclaimers</h4>
                <p className="mb-10">Toronto Real Estate Board's (“TREB“) ownership of and the validity of TREB's proprietary rights and copyright in the MLS® database, MLS® data, TREB's MLS® System, and Listing Information.</p>
                <p className="mb-10">You will not, directly or indirectly, display, post, disseminate, distribute, publish, broadcast, transfer, sell or sublicense any Listing Information to another individual or entity. The prohibited uses expressly include “scraping“ (including “screen scraping“ and “database scraping“), “data mining“ or any other activity intended to collect, store, re-organize, summarize or manipulate any Listing Information or any related data</p>
                <p className="mb-10">The Terms of Use agreement also expressly authorizes TREB, and other TREB Members or their duly authorized representatives, to access the VOW for the purposes of verifying compliance with MLS® Rules and Policies (including the VOW Rules) and monitoring the display of Members' Listings by the VOW</p>
                <p className="mb-10">Consent to the fact that your Personal Information, including first and last name, email address, and phone number may be collected, used or disclosed. The personal information may be shared with TREB for auditing and/or legal purposes.</p>
                <p className="mb-20">The information here is deemed reliable but not guaranteed by TREB</p>

                <h4 className="mb-10">The Chilliwack & District Real Estate Board, Fraser Valley Real Estate Board or Greater Vancouver REALTORS® Disclaimers</h4>
                <p className="mb-20">This representation is based in whole or in part on data generated by the Chilliwack & District Real Estate Board, Fraser Valley Real Estate Board or Greater Vancouver REALTORS® which assumes no responsibility for its accuracy.</p>

                <h4 className="mb-10">The Canadian Real Estate Association's Disclaimers</h4>
                <p className="mb-10">CREA is the owner of the REALTOR® and MLS® trademarks: “REALTOR®, REALTORS®, and the REALTOR® logo are certification marks that are owned by REALTOR® Canada Inc. and licensed exclusively to The Canadian Real Estate Association (CREA). These certification marks identify real estate professionals who are members of CREA and who must abide by CREA’s By-Laws, Rules, and the REALTOR® Code. The MLS® trademark and the MLS® logo are owned by CREA and identify the quality of services provided by real estate professionals who are members of CREA.</p>
                <p className="mb-20">The information contained on this site is based in whole or in part on information that is provided by members of The Canadian Real Estate Association, who are responsible for its accuracy. CREA reproduces and distributes this information as a service for its members and assumes no responsibility for its accuracy.</p>

                <h4 className="mb-10">Information Technology Systems Ontario Disclaimers:</h4>
                <p className="mb-10">You will make only personal, non-commercial use of the VOW Content (Virtual Office Website). You represents that you have a bona fide interest in the purchase, sale, or lease of real estate of the type being offered through the VOW. That you acknowledges entering into a lawful consumer-broker relationship with the VOW Operator. That you will not copy, redistribute, or retransmit any of the VOW Content, except in connection with your consideration of the purchase or sale of an individual property. You acknowledges the Association’s ownership of and the validity of the Association’s copyrights in the MLS® System data. That despite the preceding provisions, the Association and other Members and their duly authorized representatives may access the VOW for the purposes of verifying compliance with these Regional MLS® Rules and monitoring display of other Members’ listings by the VOW. Information deemed reliable but not guaranteed by Information Technology Systems Ontario, Inc.</p>
                <p className="mb-20">© {new Date().getFullYear()} Information Technology Systems Ontario, Inc.</p>

                <h4 className="mb-10">Copyright</h4>
                <p className="mb-20">The listing content on this website is protected by copyright and other laws, and is intended solely for the private, non-commercial use by individuals. Any other reproduction, distribution or use of the content, in whole or in part, is specifically forbidden. The prohibited uses include commercial use, “screen scraping”, “database scraping”, and any other activity intended to collect, store, reorganize or manipulate data on the pages produced by or displayed on this website.</p>
                <p className="mb-20">The content in its entirety, including text content, graphics, layouts, and all source code, belong to the owners of the web site. This term is protected by intellectual property rights and copyright law. Copying, redistribution, use or publication either for free or for monetary gain is strictly prohibited. Some of the content on the site is the copyrighted and licensed work of third parties.</p>

                <h4 className="mb-10">Terms of Use</h4>
                <ol style={{ listStyle: 'decimal', marginLeft: '20px' }}>
                  <li className="mb-10">The content of this web site in its entirety is subject to change without notice. Its purpose is for your general information only.</li>
                  <li className="mb-10">No parties guarantee the accuracy, timeliness, performance, completeness, or suitability of the content and information found on this site. You acknowledge that errors or inaccuracies may exist, and that the owners of the site are in no way liable for any such errors.</li>
                  <li className="mb-10">The owners of the site are not responsible and hold no liability for third-party content that may be posted on the site by end users, or for content that is linked to from this web site including other web sites.</li>
                  <li className="mb-10">The use of and viewing of information on this site is at your own risk. Any consequences of use that may occur are not the liability of the web site owners.</li>
                  <li className="mb-10">Unauthorized use of this web site or its contents may give rise to a claim for damages and/or be a criminal offense enforceable by local and international law.</li>
                  <li className="mb-10">We reserve the right to restrict access to certain areas of the web site at our own discretion. If a username and password, or any other access credentials, are provided to you as the end user, it is your responsibility to keep such information confidential.</li>
                  <li className="mb-10">The owners of the web site are not responsible for user-generated content, and not liable for any violations that such content may constitute, {siteContent.agent.name}'s Website SQFT data is an approximate area measurement and is not guaranteed by any means to be an exact "as build" measurement. This data should only be used as a guide and should be confirmed by a buyer.</li>
                  <li className="mb-10">This Terms of Use do not create an agency relationship with the Registrant</li>
                  <li className="mb-10">All data obtained from the MLS® VOW is intended only for the Registrant’s personal, non-commercial use that the Registrant has a bona fide interest in the purchase, sale or lease of real estate of the type being offered through the MLS®VOW</li>
                  <li className="mb-10">The Registrant will not copy, redistribute or retransmit any of the MLS® VOW Data or information provided</li>
                  <li className="mb-20">The Registrant acknowledges the Board’s copyright in the MLS® VOW Data</li>
                </ol>

              </div>
            </div>
          </div>
        </div>
        <Footer2 />
      </div>
    </>
  );
}